# gateway => https://medium.com/@gauravraisinghani1998/implementing-spring-cloud-gateway-a-comprehensive-guide-3498aaacfdca

# keycloak => https://medium.com/@iaravinda33/integrating-keycloak-authentication-with-spring-boot-a-complete-guide-98df2c8d244a
services:
  keycloak_db:
    image: postgres:18.3
    container_name: keycloak-db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${KEYCLOAK_POSTGRES_USER} -d keycloak" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./keycloak_data:/var/lib/postgresql/18/docker
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=${KEYCLOAK_POSTGRES_USER}
      - POSTGRES_PASSWORD=${KEYCLOAK_POSTGRES_PASSWORD}
    networks:
      - keycloak_network

  keycloak:
    image: quay.io/keycloak/keycloak:26.6
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak-db:5432/keycloak
      - KC_DB_USERNAME=${KEYCLOAK_POSTGRES_USER}
      - KC_DB_PASSWORD=${KEYCLOAK_POSTGRES_PASSWORD}
    ports:
      - "8000:8080"
    depends_on:
      keycloak_db:
        condition: service_healthy
    command: 'start-dev'
    networks:
      - keycloak_network

  kafka-broker-1:
    image: apache/kafka:4.2.0
    container_name: kafka-broker-1
    ports:
      - "9094:9094" # External listener for access from outside the docker network
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-1:9092,EXTERNAL://localhost:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      CLUSTER_ID: oHEo8RY0S6OV-Rzlputyeg
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-broker-1:9093,2@kafka-broker-2:9093,3@kafka-broker-3:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    volumes:
      - ./kafka-broker-1/data:/tmp/kafka-logs
    healthcheck:
      test: [ "CMD-SHELL", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092 || exit 1" ]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - kafka_network


  kafka-broker-2:
    image: apache/kafka:4.2.0
    container_name: kafka-broker-2
    ports:
      - "9095:9094" # External listener for access from outside the docker network
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-2:9092,EXTERNAL://localhost:9095
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      CLUSTER_ID: oHEo8RY0S6OV-Rzlputyeg
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-broker-1:9093,2@kafka-broker-2:9093,3@kafka-broker-3:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    volumes:
      - ./kafka-broker-2/data:/tmp/kafka-logs
    healthcheck:
      test: [ "CMD-SHELL", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092 || exit 1" ]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - kafka_network

  kafka-broker-3:
    image: apache/kafka:4.2.0
    container_name: kafka-broker-3
    ports:
      - "9096:9094" # External listener for access from outside the docker network
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-3:9092,EXTERNAL://localhost:9096
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      CLUSTER_ID: oHEo8RY0S6OV-Rzlputyeg
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-broker-1:9093,2@kafka-broker-2:9093,3@kafka-broker-3:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    volumes:
      - ./kafka-broker-3/data:/tmp/kafka-logs
    healthcheck:
      test: [ "CMD-SHELL", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092 || exit 1" ]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - kafka_network

  ### o11y & monitoring

  grafana:
    image: grafana/grafana:11.6
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana # grafana data persistence
      - ./config/grafana/grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yml # grafana datasource provisioning
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - monitoring_network
      - loki_network

  prometheus:
    image: prom/prometheus:v3
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring_network
      - loki_network

  loki-read:
    image: grafana/loki:3.7
    command: "-config.file=/etc/loki/config.yaml -target=read -query-scheduler.use-scheduler-ring=false"
    ports:
      - "3101:3100"
      - "7946"
      - "9095"
    volumes:
      - ./config/loki/loki-config.yaml:/etc/loki/config.yaml
    depends_on:
      - minio
    healthcheck:
      test: [ "CMD", "/usr/bin/loki", "-health" ]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 5
    networks: &loki-dns
      loki_network:
        aliases:
          - loki_network

  loki-write:
    image: grafana/loki:3.7
    command: "-config.file=/etc/loki/config.yaml -target=write"
    ports:
      - "3102:3100"
      - "7946"
      - "9095"
    volumes:
      - ./config/loki/loki-config.yaml:/etc/loki/config.yaml
    healthcheck:
      test: [ "CMD", "/usr/bin/loki", "-health" ]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - minio
    networks:
      <<: *loki-dns

  alloy:
    image: grafana/alloy:v1.17.1
    volumes:
      - ./config/alloy/alloy-local-config.yaml:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    ports:
      - 12345:12345
    depends_on:
      - loki-gateway
    networks:
      - loki_network

  minio:
    image: minio/minio:latest
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /data/loki-data && \
        mkdir -p /data/loki-ruler && \
        minio server /data
    environment:
      - MINIO_ROOT_USER=loki
      - MINIO_ROOT_PASSWORD=supersecret
      - MINIO_PROMETHEUS_AUTH_TYPE=public
      - MINIO_UPDATE=off
    ports:
      - "9000"
    volumes:
      - ./minio-data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 15s
      timeout: 20s
      retries: 5
    networks:
      - loki_network

  loki-backend:
    image: grafana/loki:3.7
    volumes:
      - ./config/loki/loki-config.yaml:/etc/loki/config.yaml
    ports:
      - "3100"
      - "7946"
    command: "-config.file=/etc/loki/config.yaml -target=backend -legacy-read-mode=false"
    depends_on:
      - loki-gateway
    healthcheck:
      test: [ "CMD", "/usr/bin/loki", "-health" ]
      start_period: 30s
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - loki_network

  loki-gateway:
    image: nginx:1.31
    depends_on:
      - loki-read
      - loki-write
    entrypoint:
      - sh
      - -euc
      - |
        cat <<EOF > /etc/nginx/nginx.conf
        user  nginx;
        worker_processes  5;  ## Default: 1
        
        events {
          worker_connections   1000;
        }
        
        http {
          resolver 127.0.0.11;
        
          server {
            listen             3100;
        
            location = / {
              return 200 'OK';
              auth_basic off;
            }
        
            location = /api/prom/push {
              proxy_pass       http://loki-write:3100\$$request_uri;
            }

            location = /api/prom/tail {
              proxy_pass       http://loki-read:3100\$$request_uri;
              proxy_set_header Upgrade \$$http_upgrade;
              proxy_set_header Connection "upgrade";
            }

            location ~ /api/prom/.* {
              proxy_pass       http://loki-read:3100\$$request_uri;
            }

            location = /loki/api/v1/push {
              proxy_pass       http://loki-write:3100\$$request_uri;
            }

            location = /loki/api/v1/tail {
              proxy_pass       http://loki-read:3100\$$request_uri;
              proxy_set_header Upgrade \$$http_upgrade;
              proxy_set_header Connection "upgrade";
            }

            location ~ /loki/api/.* {
              proxy_pass       http://loki-read:3100\$$request_uri;
            }
          }
        }
        EOF
        /docker-entrypoint.sh nginx -g "daemon off;"
    ports:
      - "3100:3100"
    healthcheck:
      test: [ "CMD", "service", "nginx", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - loki_network

  tempo:
    image: grafana/tempo:3.0.2
    command: -target=all -config.file=/etc/tempo.yaml
    restart: unless-stopped
    volumes:
      - ./config/tempo/tempo.yaml:/etc/tempo.yaml
      - ./tempo-data:/var/tempo
    ports:
      - "3200:3200" # tempo
      - "4317:4317" # Tempo OTLP GRPC
      - "4318:4318" # Tempo OTLP HTTP
    networks:
      - monitoring_network


  ### infrastructure

  command-db:
    image: postgres:18.3
    container_name: command-db
    environment:
      - POSTGRES_DB=command
      - POSTGRES_USER=${POSTGRES_COMMAND_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_COMMAND_DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./command-db-data:/var/lib/postgresql/18
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_COMMAND_DB_USER} -d command" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - services_network

  projection-db:
    image: postgres:18.3
    container_name: projection-db
    environment:
      - POSTGRES_DB=projection
      - POSTGRES_USER=${POSTGRES_PROJECTION_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PROJECTION_DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - ./projection-db-data:/var/lib/postgresql/18/docker
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_COMMAND_DB_USER} -d projection" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - services_network

  ### services

  api-gateway:
    build:
      context: ../e-commerce-platform
      dockerfile: api-gateway/Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - RESOURCE_SERVER_ISSUER_URI=${RESOURCE_SERVER_ISSUER_URI}
      - RESOURCE_SERVER_JWK_SET_URI=${RESOURCE_SERVER_JWK_SET_URI}
      - OAUTH2_CLIENT_ID=${OAUTH2_CLIENT_ID}
      - KEYCLOAK_AUTH_SERVER_URL=${KEYCLOAK_AUTH_SERVER_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - GATEWAY_URL=${GATEWAY_URL}
      # OTel
      - JAVA_TOOL_OPTIONS=-javaagent:/app/libs/opentelemetry-javaagent.jar
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4318
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=none
    depends_on:
      keycloak:
        condition: service_started
      kafka-broker-1:
        condition: service_healthy
      kafka-broker-2:
        condition: service_healthy
      kafka-broker-3:
        condition: service_healthy
    networks:
      - services_network
      - keycloak_network
      - kafka_network
      - monitoring_network
      - loki_network

  product:
    build:
      context: ../e-commerce-platform
      dockerfile: product/Dockerfile
    container_name: product
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - POSTGRES_COMMAND_USER=${POSTGRES_COMMAND_DB_USER}
      - POSTGRES_COMMAND_PASSWORD=${POSTGRES_COMMAND_DB_PASSWORD}
      - GATEWAY_URL=${GATEWAY_URL}
      # OTel
      - JAVA_TOOL_OPTIONS=-javaagent:/app/libs/opentelemetry-javaagent.jar
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4318
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=none
    depends_on:
      command-db:
        condition: service_healthy
      kafka-broker-1:
        condition: service_healthy
      kafka-broker-2:
        condition: service_healthy
      kafka-broker-3:
        condition: service_healthy
    networks:
      - services_network
      - kafka_network
      - monitoring_network
      - loki_network

  order:
    build:
      context: ../e-commerce-platform
      dockerfile: order/Dockerfile
    container_name: order
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - POSTGRES_COMMAND_USER=${POSTGRES_COMMAND_DB_USER}
      - POSTGRES_COMMAND_PASSWORD=${POSTGRES_COMMAND_DB_PASSWORD}
      - GATEWAY_URL=${GATEWAY_URL}
      # OTel
      - JAVA_TOOL_OPTIONS=-javaagent:/app/libs/opentelemetry-javaagent.jar
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4318
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=none
    depends_on:
      command-db:
        condition: service_healthy
      kafka-broker-1:
        condition: service_healthy
      kafka-broker-2:
        condition: service_healthy
      kafka-broker-3:
        condition: service_healthy
    networks:
      - services_network
      - kafka_network
      - monitoring_network
      - loki_network

  stock:
    build:
      context: ../e-commerce-platform
      dockerfile: stock/Dockerfile
    container_name: stock
    ports:
      - "8083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - POSTGRES_COMMAND_USER=${POSTGRES_COMMAND_DB_USER}
      - POSTGRES_COMMAND_PASSWORD=${POSTGRES_COMMAND_DB_PASSWORD}
      - GATEWAY_URL=${GATEWAY_URL}
      # OTel
      - JAVA_TOOL_OPTIONS=-javaagent:/app/libs/opentelemetry-javaagent.jar
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4318
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=none
    depends_on:
      command-db:
        condition: service_healthy
      kafka-broker-1:
        condition: service_healthy
      kafka-broker-2:
        condition: service_healthy
      kafka-broker-3:
        condition: service_healthy
    networks:
      - services_network
      - kafka_network
      - monitoring_network
      - loki_network

  projection:
    build:
      context: ../e-commerce-platform
      dockerfile: projection/Dockerfile
    container_name: projection
    ports:
      - "8084:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - POSTGRES_PROJECTION_USER=${POSTGRES_PROJECTION_DB_USER}
      - POSTGRES_PROJECTION_PASSWORD=${POSTGRES_PROJECTION_DB_PASSWORD}
      - GATEWAY_URL=${GATEWAY_URL}
      # OTel
      - JAVA_TOOL_OPTIONS=-javaagent:/app/libs/opentelemetry-javaagent.jar
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4318
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=none
    depends_on:
      projection-db:
        condition: service_healthy
      kafka-broker-1:
        condition: service_healthy
      kafka-broker-2:
        condition: service_healthy
      kafka-broker-3:
        condition: service_healthy
    networks:
      - services_network
      - kafka_network
      - monitoring_network
      - loki_network

  payment:
    build:
      context: ../e-commerce-platform
      dockerfile: payment/Dockerfile
    container_name: payment
    ports:
      - "8085:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - POSTGRES_COMMAND_USER=${POSTGRES_COMMAND_DB_USER}
      - POSTGRES_COMMAND_PASSWORD=${POSTGRES_COMMAND_DB_PASSWORD}
      # OTel
      - JAVA_TOOL_OPTIONS=-javaagent:/app/libs/opentelemetry-javaagent.jar
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4318
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=none
    depends_on:
      command-db:
        condition: service_healthy
      kafka-broker-1:
        condition: service_healthy
      kafka-broker-2:
        condition: service_healthy
      kafka-broker-3:
        condition: service_healthy
    networks:
      - services_network
      - kafka_network
      - monitoring_network
      - loki_network

  notification:
    build:
      context: ../e-commerce-platform
      dockerfile: notification/Dockerfile
    container_name: notification
    ports:
      - "8086:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      # OTel
      - JAVA_TOOL_OPTIONS=-javaagent:/app/libs/opentelemetry-javaagent.jar
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4318
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=none
    depends_on:
      kafka-broker-1:
        condition: service_healthy
      kafka-broker-2:
        condition: service_healthy
      kafka-broker-3:
        condition: service_healthy
    networks:
      - kafka_network
      - monitoring_network
      - loki_network

networks:
  keycloak_network:
    driver: bridge

  kafka_network:
    driver: bridge

  services_network:
    driver: bridge

  monitoring_network:
    driver: bridge

  loki_network:

