spring:
  datasource:
    url: jdbc:postgresql://command-db:5432/command
    username: ${POSTGRES_COMMAND_USER}
    password: ${POSTGRES_COMMAND_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  kafka:
    bootstrap-servers: kafka-broker-1:9092

app:
  scheduling:
    order: 10000
