spring:
  application:
    name: product

kafka:
  topics:
    product-created-topic: product-created-topic
    product-updated-topic: product-updated-topic
    product-deleted-topic: product-deleted-topic
  config:
    producer:
      idempotency-enabled: true
      acks: all
      max-in-flight-requests-per-connection: 5
      retries: 2147483647 # Integer.MAX_VALUE, this is the default value for retries in Spring Kafka, but we set it explicitly for clarity
app:
  scheduling:
    enabled: true


