apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: true
    editable: true

  - name: Loki
    type: loki
    access: proxy
    editable: true
    url: http://loki-gateway:3100
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
      derivedFields:
        - name: TraceID
          matcherRegex: '\[.+,(.+),.+\]'
          matcherType: regex
          datasourceUid: tempo
          urlDisplayLabel: View Trace
          url: "$${__value.raw}"
    secureJsonData:
      httpHeaderValue1: "tenant1"

  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3200
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    apiVersion: 1
    uid: tempo
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: prometheus