spring:
  application:
    name: payment

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

kafka:
  topics:
    order-ready-for-payment-topic: order-ready-for-payment-topic
    payment-processed-topic: payment-processed-topic
    payment-failed-topic: payment-failed-topic
  config:
    producer:
      idempotency-enabled: true
      acks: all
      max-in-flight-requests-per-connection: 5
      retries: 2147483647
    consumer:
      groups:
        payment-order-ready-for-payment-group: payment-order-ready-for-payment-group
      auto-offset: earliest
      json-deserializer-trusted-packages: com.eventdriven.contracts.order.event

app:
  scheduling:
    enabled: true
