# Default values for notification.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: notification-deployment
serviceName: notification-service # used by the prometheus service monitor to scrape metrics
appLabel: notification

replicaCount: 1

resources:
  requests:
    cpu: 100m
    memory: 1.5Gi
  limits:
    cpu: 500m
    memory: 1.5Gi

image:
  repository: notification
  tag: v1

containerPort: 8080

otelEnabled: true

service:
  port: 8080
  targetPort: 8080
  type: ClusterIP

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: true
  targetMemoryUtilizationPercentage: true
  resource:
    cpu:
      averageUtilization: 70
    memory:
      averageUtilization: 70

extraEnv:
  - name: KAFKA_BOOTSTRAP_SERVERS
    value: <kafka-bootstrap-servers>
