{{- define "common.deployment" -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
  labels:
    app: {{ .Values.appLabel }}
spec:
  {{ if not (.Values.autoscaling).enabled }}
  replicas: {{ .Values.replicaCount }}
  {{ end }}
  selector:
    matchLabels:
      app: {{ .Values.appLabel }}
  template:
    metadata:
      name: {{ .Values.deploymentName }}
      labels:
        app: {{ .Values.appLabel }}
    spec:
      containers:
        - name: {{ .Values.appLabel }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.containerPort }}
              protocol: TCP
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: {{ (.Values.global).configmapName }}
                  key: SPRING_PROFILES_ACTIVE
            {{ if .Values.otelEnabled }}
            - name: JAVA_TOOL_OPTIONS
              valueFrom:
                configMapKeyRef:
                  name: {{ (.Values.global).configmapName }}
                  key: JAVA_TOOL_OPTIONS
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ (.Values.global).configmapName }}
                  key: OTEL_EXPORTER_OTLP_ENDPOINT
            - name: OTEL_METRICS_EXPORTER
              valueFrom:
                configMapKeyRef:
                  name: {{ (.Values.global).configmapName }}
                  key: OTEL_METRICS_EXPORTER
            - name: OTEL_LOGS_EXPORTER
              valueFrom:
                configMapKeyRef:
                  name: {{ (.Values.global).configmapName }}
                  key: OTEL_LOGS_EXPORTER
            {{ end }}
            {{ if eq .Values.serviceType "projection" }}
            - name: POSTGRES_PROJECTION_USER
              valueFrom:
                secretKeyRef:
                  name: {{ (.Values.global).secretName }}
                  key: POSTGRES_PROJECTION_USER
            - name: POSTGRES_PROJECTION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ (.Values.global).secretName }}
                  key: POSTGRES_PROJECTION_PASSWORD
          {{ else if eq .Values.serviceType "command" }}
            - name: POSTGRES_COMMAND_USER
              valueFrom:
                secretKeyRef:
                  name: {{ (.Values.global).secretName }}
                  key: POSTGRES_COMMAND_USER
            - name: POSTGRES_COMMAND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ (.Values.global).secretName }}
                  key: POSTGRES_COMMAND_PASSWORD
          {{ end }}
          {{ with .Values.extraEnv }}
              {{ toYaml . | nindent 12 }}
          {{ end }}

      restartPolicy: Always


{{- end -}}