server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/projection
    username: ${POSTGRES_PROJECTION_USER}
    password: ${POSTGRES_PROJECTION_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9094

app:
  swagger:
    gateway-url: ${GATEWAY_URL}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
