spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_PROJECTION_HOST}:${POSTGRES_PROJECTION_PORT:5432}/projection
    username: ${POSTGRES_PROJECTION_USER}
    password: ${POSTGRES_PROJECTION_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

app:
  swagger:
    gateway-url: ${GATEWAY_URL}
