spring:
  application:
    name: projection
  liquibase:
    change-log: classpath:db/db.changelog-master.yaml

kafka:
  topics:
    product-created-topic: product-created-topic
    product-updated-topic: product-updated-topic
    product-deleted-topic: product-deleted-topic
    stock-initialized-topic: stock-initialized-topic
    stock-replenished-topic: stock-replenished-topic
    order-placed-topic: order-placed-topic
    order-confirmed-topic: order-confirmed-topic
    order-cancelled-topic: order-cancelled-topic
    payment-processed-topic: payment-processed-topic
    payment-failed-topic: payment-failed-topic
  config:
    consumer:
      groups:
        product-created-events-group: projection-product-created-group
        product-updated-events-group: projection-product-updated-group
        product-deleted-events-group: projection-product-deleted-group
        stock-initialized-events-group: projection-stock-initialized-group
        stock-replenished-events-group: projection-stock-replenished-group
        order-placed-events-group: projection-order-placed-group
        order-confirmed-events-group: projection-order-confirmed-group
        order-cancelled-events-group: projection-order-cancelled-group
        payment-processed-events-group: projection-payment-processed-group
        payment-failed-events-group: projection-payment-failed-group
      auto-offset: earliest
      json-deserializer-trusted-packages: com.eventdriven.contracts.product.event,com.eventdriven.contracts.stock.event,com.eventdriven.contracts.order.event,com.eventdriven.contracts.payment.event
