spring:
  application:
    name: projection
  liquibase:
    change-log: classpath:db/db.changelog-master.yaml

kafka:
  topics:
    product-created-topic: product-created-topic
    product-updated-topic: product-updated-topic
    product-deleted-topic: product-deleted-topic
  config:
    consumer:
      groups:
        product-created-events-group: product-created-events-group-projection
        product-updated-events-group: product-updated-events-group-projection
        product-deleted-events-group: product-deleted-events-group-projection
      auto-offset: earliest
      json-deserializer-trusted-packages: com.eventdriven.contracts.product.event
